repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-ast
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: debug-statements
      - id: requirements-txt-fixer
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies:
          - karton-core
          - magika
  - repo: 'https://github.com/adrienverge/yamllint'
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: 'https://github.com/AleksaC/hadolint-py'
    rev: v2.12.1b3
    hooks:
      - id: hadolint
  - repo: 'https://github.com/trufflesecurity/trufflehog'
    rev: v3.81.9
    hooks:
      - id: trufflehog
  - repo: 'https://github.com/PyCQA/bandit'
    rev: 1.7.9
    hooks:
      - id: bandit
  - repo: 'https://github.com/astral-sh/ruff-pre-commit'
    rev: v0.6.1
    hooks:
      - id: ruff
        args:
          - '--fix'
      - id: ruff-format
  - repo: 'https://github.com/RobertCraigie/pyright-python'
    rev: v1.1.377
    hooks:
      - id: pyright
        additional_dependencies:
          - karton-core
          - magika
