name: Build and 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ntwritecode/karton-filetype:latest
    - name: Publish Docker image
      run: |
          docker login -u ntwritecode -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push ntwritecode/karton-filetype:latest
